<a href="https://colab.research.google.com/github/JGranda11/Proyecto-ai4eng20241/blob/main/04%20-%20modelos_SL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iteraciones Modelos de aprendizaje Supervisados
En este notebook vamos a realizar los primeros acercamientos a realizar entrenamoiento de modelos de datos ya preprocesados

In [3]:
#bibliotecas de machine learning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate, ShuffleSplit

In [4]:
train = pd.read_csv('trainP.csv')

In [5]:
test = pd.read_csv('testP.csv')

In [6]:
test.shape

(296786, 57)

In [7]:
train.shape

(692500, 58)

In [8]:
train.head()

ID  ESTU_VALORMATRICULAUNIVERSIDAD  ESTU_HORASSEMANATRABAJA  \
0  904256                             6.0                      1.0   
1  645256                             4.0                      0.0   
2  308367                             4.0                      4.0   
3  470353                             5.0                      0.0   
4  989032                             4.0                      3.0   

   FAMI_ESTRATOVIVIENDA  FAMI_TIENEINTERNET  FAMI_EDUCACIONPADRE  \
0                   3.0                 1.0                  5.0   
1                   3.0                 0.0                  6.0   
2                   3.0                 1.0                  4.0   
3                   4.0                 1.0                  0.0   
4                   3.0                 1.0                  2.0   

   FAMI_TIENELAVADORA  FAMI_TIENEAUTOMOVIL  ESTU_PRIVADO_LIBERTAD  \
0                 1.0                  1.0                    0.0   
1                 1.0                  0.0                    0.0   
2                 1.0                  0.0                    0.0   
3                 1.0                  0.0                    0.0   
4                 1.0                  1.0                    0.0   

   ESTU_PAGOMATRICULAPROPIO  ...  ('PSICOLOGIA',)  ('PUBLICIDAD',)  \
0                       0.0  ...              0.0              0.0   
1                       0.0  ...              0.0              0.0   
2                       0.0  ...              0.0              0.0   
3                       0.0  ...              0.0              0.0   
4                       0.0  ...              1.0              0.0   

   ('QUIMICA',)  ('RELACIONES',)  ('VETERINARIA',)  ('AMAZONA',)  ('ANDINA',)  \
0           0.0              0.0               0.0           0.0          1.0   
1           0.0              0.0               0.0           0.0          0.0   
2           0.0              0.0               0.0           0.0          1.0   
3           0.0              0.0               0.0           0.0          1.0   
4           0.0              0.0               0.0           0.0          1.0   

   ('CARIBE',)  ('ORINOQUIA',)  ('PACIFICA',)  
0          0.0             0.0            0.0  
1          1.0             0.0            0.0  
2          0.0             0.0            0.0  
3          0.0             0.0            0.0  
4          0.0             0.0            0.0  

[5 rows x 58 columns]

In [9]:
pd.options.display.max_columns = 0
train

ID  ESTU_VALORMATRICULAUNIVERSIDAD  ...  ('ORINOQUIA',)  ('PACIFICA',)
0       904256                             6.0  ...             0.0            0.0
1       645256                             4.0  ...             0.0            0.0
2       308367                             4.0  ...             0.0            0.0
3       470353                             5.0  ...             0.0            0.0
4       989032                             4.0  ...             0.0            0.0
...        ...                             ...  ...             ...            ...
692495   25096                             2.0  ...             0.0            0.0
692496  754213                             4.0  ...             0.0            0.0
692497  504185                             3.0  ...             0.0            0.0
692498  986620                             4.0  ...             0.0            0.0
692499  933374                             6.0  ...             0.0            0.0

[692500 rows x 58 columns]

In [10]:
train.columns

Index(['ID', 'ESTU_VALORMATRICULAUNIVERSIDAD', 'ESTU_HORASSEMANATRABAJA',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET', 'FAMI_EDUCACIONPADRE',
       'FAMI_TIENELAVADORA', 'FAMI_TIENEAUTOMOVIL', 'ESTU_PRIVADO_LIBERTAD',
       'ESTU_PAGOMATRICULAPROPIO', 'FAMI_TIENECOMPUTADOR',
       'FAMI_EDUCACIONMADRE', 'RENDIMIENTO_GLOBAL', '('2018',)', '('2019',)',
       '('2020',)', '('2021',)', '('ADMINISTRACION',)', '('AGRONOMIA',)',
       '('ARTES',)', '('CIENCIAS',)', '('CINE',)', '('COMERCIO',)',
       '('COMUNICACION',)', '('CONSTRUCCION',)', '('CONTADURIA',)',
       '('DIRECCION',)', '('DISEÑO',)', '('ECONOMIA',)', '('ESTUDIOS',)',
       '('FILOLOGIA',)', '('FILOSOFIA',)', '('FINANZAS',)', '('GEOGRAFIA',)',
       '('GERENCIA',)', '('GESTION',)', '('HISTORIA',)', '('HOTELERIA',)',
       '('INGENIERIA',)', '('LENGUAS',)', '('LICENCIATURA',)',
       '('LITERATURA',)', '('MATEMATICAS',)', '('MERCADEO',)', '('MUSICA',)',
       '('NEGOCIOS',)', '('Otras',)', '('PROFESIONAL',)', 

In [11]:
test.columns

Index(['ID', 'ESTU_VALORMATRICULAUNIVERSIDAD', 'ESTU_HORASSEMANATRABAJA',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET', 'FAMI_EDUCACIONPADRE',
       'FAMI_TIENELAVADORA', 'FAMI_TIENEAUTOMOVIL', 'ESTU_PRIVADO_LIBERTAD',
       'ESTU_PAGOMATRICULAPROPIO', 'FAMI_TIENECOMPUTADOR',
       'FAMI_EDUCACIONMADRE', '('2018',)', '('2019',)', '('2020',)',
       '('2021',)', '('ADMINISTRACION',)', '('AGRONOMIA',)', '('ARTES',)',
       '('CIENCIAS',)', '('CINE',)', '('COMERCIO',)', '('COMUNICACION',)',
       '('CONSTRUCCION',)', '('CONTADURIA',)', '('DIRECCION',)', '('DISEÑO',)',
       '('ECONOMIA',)', '('ESTUDIOS',)', '('FILOLOGIA',)', '('FILOSOFIA',)',
       '('FINANZAS',)', '('GEOGRAFIA',)', '('GERENCIA',)', '('GESTION',)',
       '('HISTORIA',)', '('HOTELERIA',)', '('INGENIERIA',)', '('LENGUAS',)',
       '('LICENCIATURA',)', '('LITERATURA',)', '('MATEMATICAS',)',
       '('MERCADEO',)', '('MUSICA',)', '('NEGOCIOS',)', '('Otras',)',
       '('PROFESIONAL',)', '('PSICOLOGIA',)', '('

In [12]:
np.unique(train['RENDIMIENTO_GLOBAL'].values)

array([0., 1., 2., 3.])

In [13]:
X = train.drop(['RENDIMIENTO_GLOBAL', 'ID'],axis=1)

In [14]:
Xtest = test.drop(['ID'], axis=1)

In [15]:
y = train['RENDIMIENTO_GLOBAL'].values

In [16]:
np.unique(X)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.unique(y)

array([0., 1., 2., 3.])

In [18]:
from sklearn.model_selection import train_test_split

test_size = 0.3
val_size  = test_size/(1-test_size) # Elementos de validación


print (X.shape, y.shape)
print ("test size %.2f"%test_size)
print ("val size is %.2f (relative to %.2f) "%(val_size, 1-test_size))

#Xtv, ytv son los datos que se usan para entrenar el modelo
#Xts, yts son los datos que se usan para probar el modelo
Xtv, Xts, ytv, yts = train_test_split(X, y, test_size=test_size)
print (Xtv.shape, Xts.shape)

(692500, 56) (692500,)
test size 0.30
val size is 0.43 (relative to 0.70) 
(484750, 56) (207750, 56)


In [19]:
estimator1 = DecisionTreeClassifier(max_depth=12)
z1 = cross_validate(estimator1, Xtv, ytv, return_train_score=True, return_estimator=True,
                    scoring='accuracy', cv=ShuffleSplit(n_splits=10, test_size=0.3))

In [20]:
z1

{'fit_time': array([3.15698338, 2.77580476, 2.6454463 , 4.03778434, 2.65278053,
        2.66582656, 2.6251924 , 3.31963229, 3.47116828, 2.82228947]),
 'score_time': array([0.05939174, 0.05714607, 0.062536  , 0.07366037, 0.05159378,
        0.05269742, 0.05920529, 0.07069135, 0.05830836, 0.05284429]),
 'estimator': [DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12),
  DecisionTreeClassifier(max_depth=12)],
 'test_score': array([0.39414819, 0.39614234, 0.39509713, 0.39388688, 0.39463641,
        0.39503524, 0.39566787, 0.39594293, 0.39500774, 0.39542032]),
 'train_score': array([0.42419215, 0.42419215, 0.42492301, 0.42584248, 0.42460768,
        0.42402122, 0.42601046, 0.4237943 , 0.423

In [22]:
estimator2 = RandomForestClassifier(max_depth=15)
z2 = cross_validate(estimator2, Xtv, ytv, return_train_score=True, return_estimator=True,
                    scoring='accuracy', cv=ShuffleSplit(n_splits=10, test_size=0.3))

In [23]:
z2

{'fit_time': array([43.30920649, 44.78047037, 46.79884171, 43.54341316, 43.01157141,
        43.76972556, 44.39318013, 42.66953731, 42.46952534, 42.67750239]),
 'score_time': array([4.38493943, 4.10059118, 4.93395185, 4.2899909 , 3.64361954,
        3.95665884, 3.66494179, 3.644135  , 3.64452863, 4.52288985]),
 'estimator': [RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15),
  RandomForestClassifier(max_depth=15)],
 'test_score': array([0.40986763, 0.40992264, 0.41122916, 0.40752278, 0.40938628,
        0.40821042, 0.40821042, 0.41001891, 0.4095857 , 0.40898745]),
 'train_score': array([0.52335372, 0.52642452, 0.52472114, 0.52340676, 0.52523687,
        0.52152951, 0.52462389, 0.52498

In [24]:
from sklearn.naive_bayes import GaussianNB
estimator3 = GaussianNB()
z3 = cross_validate(estimator3, Xtv, ytv, return_train_score=True, return_estimator=True,
                    scoring='accuracy', cv=ShuffleSplit(n_splits=10, test_size=0.3))

In [25]:
z3

{'fit_time': array([0.78045988, 0.75029039, 0.92360377, 1.01354671, 0.70266819,
        0.71516514, 0.69673157, 0.69873691, 0.71358776, 0.69908357]),
 'score_time': array([0.25837421, 0.31102061, 0.30746293, 0.3275578 , 0.25279617,
        0.25747418, 0.2518878 , 0.25990248, 0.25141692, 0.26370883]),
 'estimator': [GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB(),
  GaussianNB()],
 'test_score': array([0.28975761, 0.28853361, 0.28887055, 0.29054839, 0.28898057,
        0.28898057, 0.30520887, 0.28378202, 0.28893932, 0.287399  ]),
 'train_score': array([0.28948353, 0.28895896, 0.28890002, 0.28691962, 0.28998748,
        0.2875827 , 0.30668533, 0.28402859, 0.28802476, 0.28821631])}

In [26]:
def report_cv_score(z):
    print ("test score   %.3f (±%.4f) with %d splits"%(np.mean(z["test_score"]), np.std(z["test_score"]), len(z["test_score"])))
    print ("train score  %.3f (±%.4f) with %d splits"%(np.mean(z["train_score"]), np.std(z["train_score"]), len(z["train_score"])))



In [27]:
print('Estimador 1')
report_cv_score(z1)

print('Estimador 2')
report_cv_score(z2)

print('Estimador 3')
report_cv_score(z3)

Estimador 1
test score   0.395 (±0.0007) with 10 splits
train score  0.425 (±0.0008) with 10 splits
Estimador 2
test score   0.409 (±0.0010) with 10 splits
train score  0.524 (±0.0012) with 10 splits
Estimador 3
test score   0.290 (±0.0053) with 10 splits
train score  0.290 (±0.0058) with 10 splits


In [21]:
estimator1.fit(Xtv, ytv)
estimator1.score(Xtv, ytv), estimator1.score(Xts, yts)

(0.41973182052604435, 0.396043321299639)

In [ ]:
estimator2.fit(Xtv, ytv)
estimator2.score(Xtv, ytv), estimator2.score(Xts, yts)

(0.5000887055183084, 0.4098772563176895)

In [ ]:
preds = estimator2.predict(Xtest)

In [ ]:
preds

array([1., 3., 0., ..., 0., 0., 0.])

In [ ]:
idTest = pd.DataFrame(test["ID"])

Reference = ['medio-alto', 'bajo', 'alto', 'medio-bajo']
y_preditionReference = [Reference[int(i)] for i in preds]

idTest['RENDIMIENTO_GLOBAL'] = pd.Series(y_preditionReference, name='RENDIMIENTO_GLOBAL')

In [ ]:
 idTest.head()

ID RENDIMIENTO_GLOBAL
0  550236               bajo
1   98545         medio-bajo
2  499179         medio-alto
3  782980               bajo
4  785185               bajo

In [ ]:
idTest.to_csv('submission.csv', index=False)

In [ ]:
!head submission.csv

ID,RENDIMIENTO_GLOBAL
550236,bajo
98545,medio-bajo
499179,medio-alto
782980,bajo
785185,bajo
58495,medio-bajo
705444,medio-alto
557548,medio-alto
519909,bajo
