<a href="https://colab.research.google.com/github/JGranda11/Proyecto-ai4eng20241/blob/main/06%20-%20modelos_USL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_samples, silhouette_score

from sklearn.cluster import KMeans, SpectralClustering, AgglomerativeClustering, DBSCAN


In [ ]:
train = pd.read_csv('trainP.csv')

In [ ]:
test = pd.read_csv('testP.csv')

In [ ]:
test.shape, train.shape

((296786, 57), (692500, 58))

In [ ]:
X = train.drop(['RENDIMIENTO_GLOBAL', 'ID'],axis=1)

In [ ]:
X

ESTU_VALORMATRICULAUNIVERSIDAD  ESTU_HORASSEMANATRABAJA  \
0                                  6.0                      1.0   
1                                  4.0                      0.0   
2                                  4.0                      4.0   
3                                  5.0                      0.0   
4                                  4.0                      3.0   
...                                ...                      ...   
692495                             2.0                      2.0   
692496                             4.0                      4.0   
692497                             3.0                      1.0   
692498                             4.0                      1.0   
692499                             6.0                      4.0   

        FAMI_ESTRATOVIVIENDA  FAMI_TIENEINTERNET  FAMI_EDUCACIONPADRE  \
0                        3.0                 1.0                  5.0   
1                        3.0                 0.0                  6.0   
2                        3.0                 1.0                  4.0   
3                        4.0                 1.0                  0.0   
4                        3.0                 1.0                  2.0   
...                      ...                 ...                  ...   
692495                   2.0                 1.0                  4.0   
692496                   3.0                 1.0                  1.0   
692497                   3.0                 1.0                  4.0   
692498                   1.0                 0.0                  2.0   
692499                   4.0                 1.0                  4.0   

        FAMI_TIENELAVADORA  FAMI_TIENEAUTOMOVIL  ESTU_PRIVADO_LIBERTAD  \
0                      1.0                  1.0                    0.0   
1                      1.0                  0.0                    0.0   
2                      1.0                  0.0                    0.0   
3                      1.0                  0.0                    0.0   
4                      1.0                  1.0                    0.0   
...                    ...                  ...                    ...   
692495                 1.0                  0.0                    0.0   
692496                 1.0                  0.0                    0.0   
692497                 1.0                  0.0                    0.0   
692498                 0.0                  0.0                    0.0   
692499                 1.0                  1.0                    0.0   

        ESTU_PAGOMATRICULAPROPIO  FAMI_TIENECOMPUTADOR  ...  ('PSICOLOGIA',)  \
0                            0.0                   1.0  ...              0.0   
1                            0.0                   1.0  ...              0.0   
2                            0.0                   0.0  ...              0.0   
3                            0.0                   1.0  ...              0.0   
4                            0.0                   1.0  ...              1.0   
...                          ...                   ...  ...              ...   
692495                       1.0                   1.0  ...              0.0   
692496                       0.0                   1.0  ...              1.0   
692497                       1.0                   1.0  ...              0.0   
692498                       1.0                   1.0  ...              1.0   
692499                       0.0                   1.0  ...              1.0   

        ('PUBLICIDAD',)  ('QUIMICA',)  ('RELACIONES',)  ('VETERINARIA',)  \
0                   0.0           0.0              0.0               0.0   
1                   0.0           0.0              0.0               0.0   
2                   0.0           0.0              0.0               0.0   
3                   0.0           0.0              0.0               0.0   
4                   0.0           0.0              0.0               0.0   
...                 

In [ ]:
Xtest = test.drop(['ID'], axis=1)

In [ ]:
y = train['RENDIMIENTO_GLOBAL'].values

In [ ]:
print(np.unique(X))
print(np.unique(y))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3.]


In [ ]:
# K-Means clustering
estimator1 = KMeans(n_clusters=4)
estimator1.fit(X)


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=4)

In [ ]:
prediction = estimator1.predict(Xtest)
prediction.shape

(296786,)

In [ ]:
estimator1.score(X, y)

-8507724.865090605

In [ ]:
estimator1.cluster_centers_

array([[3.07187935e+00, 2.52983450e+00, 2.33141151e+00, 8.87925054e-01,
        4.74216638e+00, 8.43892193e-01, 2.92239824e-01, 9.56924063e-06,
        4.80308895e-01, 8.89178624e-01, 3.57939360e+00, 2.41451080e-01,
        2.65680397e-01, 2.45632838e-01, 2.47235686e-01, 2.00910992e-01,
        1.15309350e-03, 3.35880346e-03, 7.17214585e-03, 1.22964742e-03,
        4.86117424e-03, 1.98035435e-02, 1.16744736e-03, 8.63193351e-02,
        7.46400769e-04, 1.05022416e-02, 1.04400415e-02, 4.44969689e-04,
        6.07646780e-04, 1.33490907e-03, 4.14826581e-03, 1.77987876e-03,
        1.77030952e-04, 3.54061903e-03, 1.21050894e-03, 6.12431401e-04,
        2.26389095e-01, 2.94254149e-03, 1.01166012e-01, 3.82769625e-04,
        1.07175495e-03, 9.89459481e-03, 1.72246331e-03, 1.43251532e-02,
        1.90308273e-01, 1.38753989e-04, 7.29941675e-02, 2.47364870e-03,
        4.29658904e-03, 1.30620135e-03, 9.06685550e-03, 4.58366626e-03,
        7.00626307e-01, 1.71897054e-01, 1.44495534e-02, 1.084434

In [ ]:
idTest = pd.DataFrame(test["ID"])

Reference = ['bajo', 'medio-bajo', 'medio-alto', 'alto']
y_preditionReference = [Reference[int(i)] for i in prediction]

idTest['RENDIMIENTO_GLOBAL'] = pd.Series(y_preditionReference, name='RENDIMIENTO_GLOBAL')

In [ ]:
idTest.to_csv('submissionKm.csv', index=False)

In [ ]:
!head submissionKm.csv

ID,RENDIMIENTO_GLOBAL
550236,medio-alto
98545,medio-bajo
499179,medio-alto
782980,alto
785185,medio-alto
58495,alto
705444,medio-bajo
557548,bajo
519909,medio-alto
